<?php
require_once __DIR__ . '/vendor/autoload.php';
// Read user ids generated by user_ids_grabber.py
$user_ids = file("instagram_user_ids.txt", FILE_IGNORE_NEW_LINES);
$allData = array();
foreach($user_ids as $value){
    if( !file_exists ('data\\' . $value . '.json') ) {
        $media = Bolandish\Instagram::getAllMediaByUserID($value);
        if ($media) {
            file_put_contents('data\\' . $value . '.json', json_encode($media));
        }
    }
}
?>